---

# creates a deploy user, enables as sudoer, uploads public key.
#
# warning: this should run as root. deploy with
#          ansible-playbook [...] --ask-pass

- name: create deploy user
  user:
    name: "{{ user }}"
    createhome: yes
    home: "/home/{{ user }}/"
    shell: /bin/bash
  tags:
    - user-bootstrap

- name: back up sudoers file
  command: cp -f /etc/sudoers /etc/sudoers.tmp
  tags:
    - user-bootstrap

- name: add user to sudoers
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^{{ user }}' line='{{ user }} ALL=(ALL) NOPASSWD:ALL'
  tags:
    - user-bootstrap

- name: validate and replace sudoers file
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  tags:
    - user-bootstrap

- name: upload public key
  authorized_key: user="{{ user }}" key="{{ lookup('file', 'id_rsa.pub') }}"
  tags:
    - user-bootstrap
